# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: rezaloo/jdk8k8s
        auth:
          username: rezaloo  # can specify string literal values
          password: $DOCKERHUB_PASSWORD  # or project environment variable reference

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m
      IMAGE_NAME: trade-api-${CIRCLE_BUILD_NUM}

    # machine: true
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "pom.xml" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      # build code
      - run: mvn integration-test

      # build docker image and deploy to Quay repository
      - setup_remote_docker:   # (2)
            docker_layer_caching: true # (3)

      - run: docker build -t trade-api .

      - run: docker tag trade-api quay.io/rezaloo/rtype/${IMAGE_NAME}

      - run: docker login https://quay.io/repository/ -u rezaloo -p ${QUAY_PASSWORD}

      - run: docker push quay.io/rezaloo/rtype/${IMAGE_NAME}

      - run: kubectl set image deployment trade-api trade-api=quay.io/rezaloo/rtype/${IMAGE_NAME} --namespace team-product




